### ISSUE TITLE
Percentage empty/full sensor

### ISSUE THREAD

**Issue by robwolff3** [j9brown/esphome-seelevel#1]
Hey @j9brown , love what you've done here with this project. I had been searching for a solution to read the Seelevel II sensors in my Airstream and finally had success with your project!

The wall mounted Seelevel II monitor returns a percentage empty/full value when reading the tank sensors. Would that be possible with your project?

**Comment by j9brown** [comment]
Sure!  Try using a [multiply](https://esphome.io/components/sensor/index.html#multiply) filter.

Something like this excerpt, perhaps...

```yaml
sensor:
  - platform: seelevel
       level:
            name: "Water Level"
            filters:
              # Divide by the number of segments, here we assume you have 9 segments
              - multiply: !lambda return 1.f / 9;
       # etc...
```

Alternatively, if you have calibrated the volume sensor for your tank dimensions, you can use the copy sensor to make another sensor with the percentage just by dividing by the total volume.  You'll need to assign an id to the volume sensor first.

```yaml
sensor:
  - platform: seelevel
      volume:
        id: tank1_volume
     # etc...
  - platform: copy
    source_id: tank1_volume
    name: "Tank 1 Percent Full"
    filters:
      # Divide by the tank volume in liters, here we assume it's 40
      - multiply: !lambda return 1.f / 40;
```

ESPHome has many filters like this for processing sensor data.  You might find many of them useful for other things: https://esphome.io/components/sensor/#sensor-filters

**Comment by robwolff3** [comment]
This worked great! Thank you!!!

My configuration if anyone else is curious:
```
sensor:
  - platform: seelevel
    tank: 1
    segments: 10
    level:
      name: "Water Level"
      unit_of_measurement: "%"
      accuracy_decimals: 0
      filters:
        - multiply: !lambda return 1.f / .09;
    update_interval: 60s
```
